---
- hosts: macbooks
  #hosts: localhost
  #connection: local

  vars_files:
    - vars/homebrew.yml
    - vars/dock.yml

  # This variables are used in multiple roles
  vars:
    macsetup_homebrew_cask_appdir: ~/Applications # also used in ./vars/dock.yml

  roles:
#    - role: drew_kun.homebrew
#      homebrew_installed_packages: "{{ macsetup_homebrew_installed_packages }}"
#      homebrew_uninstalled_packages: []
#      homebrew_upgrade_all_packages: no
#      homebrew_taps: "{{ macsetup_homebrew_taps }}"
#      homebrew_cask_apps: "{{ macsetup_homebrew_cask_apps }}"
#      homebrew_cask_uninstalled_apps: []
#      homebrew_cask_appdir: "{{ macsetup_homebrew_cask_appdir }}"
#      homebrew_use_brewfile: yes
#      homebrew_brewfile_dir: '~'

#    - role: drew_kun.macdock
#      macdock_remove_all: no
#      macdock_remove_items: "{{ macsetup_remove_dockitems }}"
#      macdock_add_items: "{{ macsetup_add_dockitems }}"

    - role: drew_kun.macos_terminal

#    - role: drew_kun.ohmyzsh

#    - role: drew_kun.pf

#    - role: drew_kun.sshd
...
