---
- hosts: macbooks
#- hosts: localhost
#  connection: local

  vars_files:
  - vars/geerlingguy.homebrew.yml
  - vars/drew-kun.mas.yml
  - vars/drew-kun.macdock.yml
  - vars/drew-kun.vim.yml
  - vars/vault.yml
  - vars/feffi.macos-defaults/system.yml
  - vars/feffi.macos-defaults/finder.yml
  - vars/feffi.macos-defaults/appstore.yml

  pre_tasks:
  - name: "[pre_tasks] Include vars from Darwin.yml"
    include_vars: Darwin.yml
    when: not ansible_distribution_version.startswith('10.13')

  # Starting with MacOS 10.13 the Grab app is changed in favour of Screenshot:
  - name: "[pre_tasks] Include vars from Darwin_pre_10.13.yml if running pre-Mojave MacOS version"
    include_vars: Darwin_pre_10.13.yml
    when: ansible_distribution_version.startswith('10.13')

  roles:
#  - role: geerlingguy.homebrew  # TESTED

#  - role: drew-kun.mas

#  - role: drew-kun.macdock  # TESTED

#  - role: drew-kun.nerdfonts  # TESTED

#  - role: drew-kun.terminus_powerline # TESTED

#  - role: drew-kun.macos_terminal  # TESTED
#    macos_terminal_colorscheme: Cipherpunk  # Solarized_Dark_Custom | Nord_Custom | Cipherpunk

#  - role: drew-kun.ohmyzsh  # TESTED  (ColorLS does not work)
#
#  - role: drew-kun.vim  # TESTED

#  - role: drew-kun.mpd

#  - role: drew-kun.pf

#  - role: drew-kun.sshd
#    sshd_certs: yes
#    sshd_cert_id: "{{ vault_sshd_cert_id }}"
#    sshd_users: "{{ vault_sshd_users }}"


## DEFAULTS:
#  - role: feffi.macos-defaults
#    macos_defaults:
#      defaults: "{{
#        macsetup_defaults_system +
#        macsetup_defaults_finder +
#        macsetup_defaults_appstore }}"

#  post_tasks:
#  ## REBOOT
#  # Since for now there is no way to run external handlers when change is detected within imported role,
#  # rebooting the managed host unconditionaly for changes in NSGlobalDomain to take effect.
#  - name: '[macsetup] Reboot the managed host to reload kernel modules'
#    shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
#    async: 1
#    poll: 0
#    become: yes
#    tags:
#    - macsetup
#    - macsetup_reboot
#
#  # ansible_ssh_host variable is set in ansible inventory (hosts) file
#  - name: '[macsetup] Waiting for managed host to come back after reboot'
#    wait_for:
#      host: "{{ ansible_ssh_host }}"
#      port: 22
#      delay: 1
#    delegate_to: localhost
#    tags:
#    - macsetup
#    - macsetup_reboot
...
